### PR TITLE
Fixing WIN32 incompatibilities

### LINKED ISSUE #28: Compile On Windows
Get ddb library, cmd line app and NodeJS bindings to compile on Windows.

### PR DESCRIPTION
**Pull request by pierotofy**
Closes #28 

This still needs some work.

@HeDo88TH once it's ready just ping here 👍

### CODE REVIEW

File: classes/dsmservice.cpp [hunk 1]
```diff
@@ -104,7 +104,7 @@ std::string DSMService::loadFromNetwork(double latitude, double longitude){
     std::string filename = std::to_string(static_cast<int>(p.x)) + "_" +
                            std::to_string(static_cast<int>(p.y)) + "_" +
                            std::to_string(std::chrono::system_clock::now().time_since_epoch().count()) + ".tif";
-    fs::path filePath = getCacheDir() / filename;
+    std::string filePath = getCacheDir().string(); // filename
```
Comment (pierotofy) [inline classes/dsmservice.cpp:107]: Note `/` is a concatenation operator. Should be: `(getCacheDir() / filename).string()`

Comment (HeDo88TH) [reply classes/dsmservice.cpp:107]: Ok I fix it
